version: '3.4'

services:
  node:
    build:
      context: .
    image: akafts/bandexbot
    command: nodemon bot.js
    volumes:
      - ./src:/opt/app
      - ./storage:/opt/storage
    secrets:
      - bot_token

secrets:
  bot_token:
    file: ./bot_token.txt
